### PR TITLE
Rename test:ci.sh to test.ci.sh

### PR DESCRIPTION
**Pull request by ryanraposo**
On Windows, `:` is a reserved character, files cannot be created with it in the name (https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file). Most immediately, this prevents a successful clone on Windows without tampering with Git settings that aren't worth changing.

- Change the name of `test:ci.sh` to `test.ci.sh`
- Update lock files
- Update scripts

### CODE REVIEW

**Comment by ryanraposo** [comment]
Hard to test the tests. Let me know how these changes go.

**Comment by Dj-Viking** [comment]
Server tests failed..not sure why my env wasnt exposed in the ci

**Comment by Dj-Viking** [comment]
@ryanraposo Can you please tell me your node and npm versions? differing npm versions becomes problematic with dependencies

And I'll address the other issue you opened about setup, I have not included what the env vars configuration needs to be for running the server.

**Comment by Dj-Viking** [comment]
Actually I am thinking of just removing the file altogether just to make it simpler. not sure what I was thinking to make this file and name it like that randomly. simply running the npm script from the package.json is just fine in most cases.

**Comment by Dj-Viking** [comment]
Actually I am thinking of just removing the file altogether just to make it simpler. not sure what I was thinking to make this file and name it like that randomly. simply running the npm script from the package.json is just fine in most cases.

**Comment by Dj-Viking** [comment]
@ryanraposo  Also I just realized it doesn't matter much what your node and npm versions are because the CI runs in the same defined environment every time it even has the env vars as github secrets in the yml so the actions runner is fine. I want to get your build working at least. there might be a couple of env vars that just have to be missing for now. but I can show you how to get them working.

**Comment by ryanraposo** [comment]
What's in env.txt? And .env? What would development look like for me if not privy to that information? 

If you could just lmk what the norm is vs what to expect here. Maybe include the former in that doc issue

**Comment by Dj-Viking** [comment]
For this project didnt care to use dotenv package so just reading in the local file env.txt and extending the key value pairs into the process.env object. I will address this in #133

**Review by Dj-Viking — CHANGES_REQUESTED** [review]
Hey Ryan thanks again for the PR! I really appreciate the help! I think we'll just remove the shell file altogether. and your lock file changes aren't going to work quite right on my computer because i am using a different node and npm version on my local machine at the moment. so for now let's remove your package.json lock file changes from the PR and we should be good to go. you can always have those changes on your local machine, but just not ever staging the changes so they're not added to the branch itself. 

I will do an update to the packages on my end to get latest versions and push that to main, then you just pull latest main and see if it works. If the install still isn't clean then you'll have to work with your lockfile version that your npm creates for you and leave those as unstaged changes on your local machine 👍 

Let's try this and see how it goes!

**Comment by ryanraposo** [comment]
> Hey @ryanraposo thanks again for the PR! I really appreciate the help! I think we'll just remove the shell file altogether. and your lock file changes aren't going to work quite right on my computer because i am using a different node and npm version on my local machine at the moment. so for now let's remove your package.json lock file changes from the PR and we should be good to go. you can always have those changes on your local machine, but just not ever staging the changes so they're not added to the branch itself.
> 
> I will do an update to the packages on my end to get latest versions and push that to main, then you just pull latest main and see if it works. If the install still isn't clean then you'll have to work with your lockfile version that your npm creates for you and leave those as unstaged changes on your local machine 👍
> 
> Let's try this and see how it goes!

Np! I'll give this a shot sometime this afternon. Saw the docs pr just now 👍

**Comment by ryanraposo** [comment]
Let's drop this PR for a new one that better reflects the suggested changes

**Pull request closed without merging**
